<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Playwright" Version="1.60.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="YoutubeDLSharp" Version="1.2.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Services.Abstraction\Services.Abstraction.csproj" />
  </ItemGroup>

</Project>
